# Use root/example as user/password credentials
version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME_ADMIN}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD_ADMIN}
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME_ADMIN}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD_ADMIN}
      ME_CONFIG_MONGODB_URL: mongo://${DB_USERNAME_ADMIN}:${DB_PASSWORD_ADMIN}@mongo:27017/
